import type { Metadata } from "next";
import type { ReactNode } from "react";
import "@mantine/core/styles.css";
import {
  createTheme,
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Bryan Laporte | Profile",
};

const theme = createTheme({
  fontFamily: "Roboto, Arial, Verdana, sans-serif",
  headings: {
    fontWeight: "500",
  },
});

const Layout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="en" {...mantineHtmlProps} className={roboto.className}>
      <head>
        <ColorSchemeScript
          defaultColorScheme="auto"
          nonce="8IBTHwOdqNKAWeKl7plt8g=="
        />
      </head>
      <body>
        <MantineProvider defaultColorScheme="auto" theme={theme}>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
};

export default Layout;
